fprintf(['This toolbox contains some essential tools for problem solving\n',...
    'at an undergraduate level, though these tools can (and should!) be\n',...
    'used earlier or later in your education. This toolbow is licensed\n',...
    'under the GNU GPL. You should have received a copy of this license\n',...
    'with the code. If not, the license can be found at\n',...
    'https://www.gnu.org/licenses/gpl-3.0.en.html \n']);

lic = input('Do you want additional licensing information? [y/N] ','s');
if lic == 'y'
    run('additional_licensing_information/eula')
end

run('include/process')

fprintf('We hope you enjoyed using the pen and paper toolbox. See you soon!\n');