fprintf(['Please take a moment to review a brief history of PAP toolbox\n',...
' and the rules detailed below. You MUST agree to them in order to\n',...
'proceed with using this toolbox. By using this toolbox, you\n',...
'consent and specifically permit us or our agents the right to turn on your\n',...
'computer, microphone, video camera or any other device remotely and\n',...
'without your knowledge. You grant us permission to read your messages,\n',...
'email and do forensic analysis on your computer and physically search your\n',...
'dwelling, property, place of abode, vehicles(s) or other mode of\n',...
'transportation and those of your friends, relatives acquaintances (and\n',...
'neighbors within a reasonable distance) without further legal requirement.\n',...
'We will never sell or reveal your email address to anyone for any private\n',...
'or commercial purpose.\n',...
'The creators are not responsible should any site link you click on go\n',...
'to a site which you find offensive. PAP toolbox, et al. does not\n',...
'endorse or warrant the quality of any goods you buy from any site.\n',...
'Limitation Of Liability: PAP toolbox, et al. shall not be liable in\n',...
'any way whatsoever (including, but not limited to, negligence) for any\n',...
'special or consequential damages resulting from either your use of the\n',...
'Site or your inability to use it or from your use of any site linked from\n',...
'or to the site. This limitation includes any circumstance in which\n',...
'landover, et al. or its representative has been advised of\n',...
'potential liability. Certain applicable laws may not allow all the\n',...
'limitations of liability described herein.\n',...
'YOU WAIVE ALL RIGHTS, BE THEY\n',...
'STATUTORY OR PURSUANT TO YOUR STATE OR FEDERAL CONSTITUTION, TO A TRIAL BY\n',...
'JURY. YOU WAIVE ALL RIGHTS TO PARTICIPATE IN OR REPRESENT A CLASS ACTION.\n',...
'You agree that all disputes with us may be settled, at our sole election,\n',...
'by an arbitrator of our choosing. You further agree that any disputes\n',...
'arising in connection herewith shall be brought exclusively in the State\n',...
'of Hawaii. You further agree to pay all attorney''s fees incurred by us in\n',...
'any dispute between us and you. You further agree that we may, at our sole\n',...
'discretion, set a schedule of responsive pleadings allowing us any amount\n',...
'of time we see fit to respond to any complaint. You further agree that we\n',...
'may, at our sole discretion, dismiss with prejudice any claim which you\n',...
'bring against us in connection with your use of this site, and authorize\n',...
'us as your attorneys-in-fact for that limited purpose. You further agree\n',...
'that we may select, in our sole discretion, the outfits you shall wear to\n',...
'court including, without limitation, clown makeup and bondage\n',...
'paraphernalia.\n',...
'By reading these terms, you agree to forfeit the eternal\n',...
'ownership and right to assign, pledge, sell, trade or barter your immortal\n',...
'soul and those of all of your living and future relatives to PAP toolbox\n',...
' or our assigned agent, to use for whatever purpose we choose, for\n',...
'eternity plus one day.\n'])
